### ISSUE TITLE
Keyboard patterns

### ISSUE THREAD

**Issue by ncou** [rschwietzke/yetanotherpasswordmeter#3]
Hi,

First : this is a very nice tool.

If you are interested, here are a few keyboard patter (french keyboard) and numeric pattern that you could perhaps add to your library : 

this.KeyboardPatterns =
	{
		// german and english and french keyboard text
		data: [	........

		        "azertyuiop^$qsdfghjklmù*<wxcvbn,;:!","&é\"'(-è_çà)=", // fr
		        "aqwzsxedcrfvtgbyhnuj,ik;ol:pm!^ù$*", // fr up-down

		        "0321654987", "7894561230", "9876543210", "0147258369", // reverse numeric
		        "abcdefghijklmnopqrstuvwxyz"// alphabet

		],

I suppose i could post a pull request, but i am a total newbie in Git.

**Comment by rschwietzke** [comment]
Hi, thanks. Feel free to try it. I do not have much time right now  to work on the project. Rene

**Comment by ncou** [comment]
Done i made my first pull request :)

**Comment by rschwietzke** [comment]
Thank you. Merged it.
